modLoader="javafml"
loaderVersion="[26,)"
#logoFile="quickleafdecay.png" #optional
authors="CJMinecraft" #optional
displayURL="https://minecraft.curseforge.com/projects/reload-audio-driver-rad" #optional
issueTrackerURL="https://github.com/CJMinecraft01/ReloadAudioDriver/issues" #optional

[[mods]]
    modId="rad" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Reload Audio Driver" #mandatory
    description='''
    Reloads the audio driver when pressing F3 + R.
    '''

[[dependencies.sct]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
